### ISSUE TITLE
Error while compiling on ubuntu server

### ISSUE THREAD

**Issue by newsocialifecom** [kripken/BananaBread#19]
i get the following error when trying to compile in ubuntu server 12.10

``` error
/usr/bin/llvm-dis: unknown type in type table
emcc: src/web/client.bc: warning: Not valid LLVM bitcode
/usr/bin/llvm-dis: unknown type in type table
llvm-link: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /usr/bin/llvm-link -help
Traceback (most recent call last):
  File "/root/games/emscripten/emcc", line 912, in <module>
    shared.Building.link(linker_inputs, in_temp(target_basename + '.bc'), remove_duplicates=remove_duplicates)
  File "/root/games/emscripten/tools/shared.py", line 702, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output + '\nemcc: If you get duplicate symbol errors, try --remove-duplicates'
AssertionError: Linking error: 
emcc: If you get duplicate symbol errors, try --remove-duplicates
make: *** [client] Error 1
```

**Comment by Huntebright89** [comment]
I have a gay problem
